### ISSUE TITLE
Issue with wallet password when it contains a '\' character

### ISSUE THREAD

**Issue by bboerst** [eth2-educators/eth2-docker#112]
I ran into a small bug when my Wallet password has a `\` character in it. When the password is [written to the password.txt](https://github.com/eth2-educators/eth2-docker/blob/ad5d2a0189acafab5961ed42cd3323564262e694/prysm/create-prysm-validator-wallet.sh#L54) file, the `\` is omitted.

For example, a password entered as `12345\abcdef` is written to password.txt as `12345abcdef`. As a result, the validator complains that the wallet password is incorrect.

**Comment by danbryan** [comment]
Thanks for the feedback, once this is merged the additional -r flags on the read call should resolve this.
