### ISSUE TITLE
ERROR: Service 'validator-import' failed to build: invalid reference format

### ISSUE THREAD

**Issue by 10ofDisks** [eth2-educators/eth2-docker#126]
I'm trying to get eth2-docker setup for pyrmont... I decided to start from scratch... I did a system update, wiped all the containers, images and volumes from Docker, created a new eth2-docker directory, did a new clone, and started the build, but got a 
`ERROR: Service 'validator-import' failed to build: invalid reference format
` 
... I see some red lines in the build log that say 
`file eth2deposit.py (for module eth2deposit) not found`
The last output of the build is:
```
Building beacon
Step 1/11 : ARG DOCKER_TAG
Step 2/11 : FROM sigp/lighthouse:${DOCKER_TAG}
ERROR: Service 'beacon' failed to build: invalid reference format
```
 Any thoughts?

**Comment by 10ofDisks** [comment]
UPDATE: I think it's a syntax error in default.env where it references the docker tag for the Lighthouse version, "v0.3.4" was not working, my workaround was changing it to "latest":
```
LH_DOCKER_TAG=latest
#LH_DOCKER_TAG=v0.3.4 # eventually stable or stable-latest when sigp introduce that
```

**Comment by yorickdowne** [comment]
Right on the nose. That comment needed to be on a line of its own. My deepest apologies. Closing this as it's now resolved in `master`.
