### ISSUE TITLE
Openethereum user issue

### ISSUE THREAD

**Issue by fredfortier** [eth2-educators/eth2-docker#147]
I'm experiencing an issue with using `Dockerfile.source` of openethereum in my docker-compose definition. I've configured `OE_USER` along with other parameters in `.env`. Looks like a leftover default.
```
Step 18/19 : COPY --chown=openethereum:openethereum --from=builder /openethereum/target/x86_64-alpine-linux-musl/release/openethereum /usr/local/bin
ERROR: Service 'eth1' failed to build: unable to convert uid/gid chown string to host mapping: can't find uid for user openethereum: no such user: openethereum
```

**Comment by adrienlacombe** [comment]
I failed to replicate just now, eth2-docker updated to latest, OE_DOCKERFILE=Dockerfile.source and OE_USER=openethereum.

**Comment by yorickdowne** [comment]
Glad to hear it worked for you! Closing for now.
