### ISSUE TITLE
TLS for Grafana

### ISSUE THREAD

**Issue by danbryan** [eth2-educators/eth2-docker#177]
16 hours

**Comment by danbryan** [comment]
Created documentation and automations for TLS communication

easy RSA
openssl x509

**Comment by yorickdowne** [comment]
So as to make this not dependent on any one provider, I am thinking traefik and cert-manager, https://cert-manager.io/docs/

I've been thinking of ways this can be done for distributed and solo staker setups, and my current thinking is that these use cases will need to be handled in separate yml files. I see no way to square that circle, where single-directory deployment remains simple and secure, while also allowing distributed deployment.

**Comment by yorickdowne** [comment]
Implemented
