### ISSUE TITLE
prysm-web claims wrong wallet password

### ISSUE THREAD

**Issue by ardevd** [eth2-educators/eth2-docker#224]
Followed the guide but when bringing docker-compose up and importing my wallet through the Prysm web interface I first notice a bunch of errors popping up saying `Head block of chain was nil`.

When restarting docker-compose and checking the validator container logs, I get the following:
```
"validator_1                 | time="2021-05-03 19:11:21" level=warning msg="Running on the Prater Testnet" prefix=flags
validator_1                 | time="2021-05-03 19:11:21" level=info msg="Enabling web portal to manage the validator client" prefix=node
validator_1                 | time="2021-05-03 19:11:21" level=info msg="Opened validator wallet" keymanager-kind=direct prefix=node wallet="/var/lib/prysm/direct"
validator_1                 | time="2021-05-03 19:11:21" level=error msg="could not read keymanager for wallet: could not initialize imported keymanager: failed to initialize account store: wrong password for wallet entered: invalid checksum" prefix=main
```

I have verified that the password stored in `password.txt` in `/var/lib/prysm/password.txt` is the exact same one I submitted through the web interface. I've scrapped the containers and volumes and run `docker-compose run --rm validator-import` again to repeat the process multiple times with no results. 

What am I missing here?

**Comment by danbryan** [comment]
I remember prysm web not respecting the docker import command when using the web interface.  I believe the solution i used was to create a new wallet in prysm web interface, then import the keys using the web gui.   If this works, can you propose some wording on how others can avoid this in the future, and I can update the docs site?

**Comment by ardevd** [comment]
Hmm, what docker import command are you referring to? If I exec into the container the password file is there. Not exactly sure how the prysm web interface correlates the wallet passwords.

**Comment by danbryan** [comment]
wallet is different from keystore.

Check out this article.

https://docs.prylabs.network/docs/wallet/nondeterministic/

**Comment by ardevd** [comment]
But the password.txt contains the wallet password does it not? Perhaps my wording in my previous post was unclear. I'm only talking about the wallet password which is what Prysm seems to be struggling with for me.

**Comment by ardevd** [comment]
Just went through the entire process and encountered the same error. Prysm looked very happy after bringing up everything with docker-compose, but after bringing it down and back up again I get the same error:

```
validator_1                 | time="2021-05-04 08:12:44" level=warning msg="Running on ETH2 Mainnet" prefix=flags
validator_1                 | time="2021-05-04 08:12:44" level=info msg="Enabling web portal to manage the validator client" prefix=node
validator_1                 | time="2021-05-04 08:12:44" level=info msg="Opened validator wallet" keymanager-kind=direct prefix=node wallet="/var/lib/prysm/direct"
validator_1                 | time="2021-05-04 08:12:44" level=error msg="could not read keymanager for wallet: could not initialize imported keymanager: failed to initialize account store: wrong password for wallet entered: invalid checksum" prefix=main
```

Any ideas on how to troubleshoot this?

**Comment by ardevd** [comment]
> I remember prysm web not respecting the docker import command when using the web interface. I believe the solution i used was to create a new wallet in prysm web interface, then import the keys using the web gui. If this works, can you propose some wording on how others can avoid this in the future, and I can update the docs site?

I don't think you can create a new wallet in the prysm web interface. Import is the only option.

**Comment by ardevd** [comment]
I eventually got it working by manually importing the validator account with the prysm cli and then creating the password.txt manually.
