### ISSUE TITLE
the method web3_clientVersion does not exist/is not available

### ISSUE THREAD

**Issue by ardevd** [eth2-educators/eth2-docker#225]
Going through the Ethereum staking checklist I'm encountering the following error when trying to assert connectivity between the Prysm beacon node and the geth instance.

```
curl -H "Content-Type: application/json" -X POST --data '{"jsonrpc":"2.0","method":"web3_clientVersion","params":[],"id":67}' http://eth1:8545
{"jsonrpc":"2.0","id":67,"error":{"code":-32601,"message":"the method web3_clientVersion does not exist/is not available"}}
```

any ideas?

**Comment by yorickdowne** [comment]
Thank you for this report. I've enabled that more broadly across all eth1 client options. This should be in a release MoreSoonerish.

**Comment by yorickdowne** [comment]
This has now been released. Closing
