### ISSUE TITLE
Support Third-Party Beacon Node

### ISSUE THREAD

**Issue by sinasabet81** [eth2-educators/eth2-docker#229]
Similar to using a third-party API for the accompanying eth1 node, it should be possible to use a third-party API in place of a locally running beacon node.

For instance, Infura has support for generating eth2 API endpoints for your project; it'd be great if part of the config of this project was an option to leverage something like this.

An example advantage to this method compared to running your own beacon chain locally is not having to wait for any sync time, or being able to run _just a validator_ on cheaper hardware.

**Comment by yorickdowne** [comment]
That's an interesting use case. I believe the Infura beacon endpoint works with Teku and Lighthouse validators.

I'll take a look at this.

**Comment by yorickdowne** [comment]
Closing with #232
