### ISSUE TITLE
Investigate and document a way to test the mnemonic

### ISSUE THREAD

**Issue by yorickdowne** [eth2-educators/eth2-docker#24]
And restore from mnemonic also seems like a good idea to be documented.

**Comment by danbryan** [comment]
Added to official docs

https://eth2-docker.net/docs/Usage/ConfigureWallet#test-your-seed-phrase

**Comment by Continuities** [comment]
When I follow these instructions, I get `Error: no such option: --validator_start_index`
When I remove the --validator_start_index flag, I get `Error: Invalid value for '--folder': Directory 'seed_checker' does not exist.` despite the folder very much existing and being accessible.
Version mismatch, I assume?

**Comment by danbryan** [comment]
@Continuities Thanks, we will be fixing shortly.  Here is a PR you can see
https://github.com/eth2-educators/eth2-docker/pull/207

should be approved soon
